"""auto

Revision ID: f390563d70c3
Revises: fbe989d444d2
Create Date: 2025-02-27 19:10:54.420691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f390563d70c3'
down_revision: Union[str, None] = 'fbe989d444d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'summary')
    op.drop_column('document_chunks', 'page_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('document_chunks', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
