"""auto

Revision ID: fbe989d444d2
Revises: f37affddc795
Create Date: 2025-02-27 15:54:56.124676

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fbe989d444d2"
down_revision: Union[str, None] = "f37affddc795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector;"))
    op.add_column(
        "document_chunks",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding")
    op.execute(sa.text("DROP EXTENSION IF EXISTS vector;"))
    # ### end Alembic commands ###
